name: model-training
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v3
      - name: Setup Python and install requirements
      - uses: actions/setup-python@v3
        with:
         python-version: '3.10'
      - run: pip install -r requirements
      - name: Train model
      - uses: actions/upload-artifact@v4
        with:
          name: baummethoden_lr.pickle
          path: data\models\baummethoden_lr.pickle
